name: Secrets and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zugriff auf Secrets
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_EMAIL: ${{ secrets.VITE_EMAIL }}
          VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}

        run: |
          echo $VITE_FIREBASE_API_KEY
          echo $VITE_FIREBASE_AUTH_DOMAIN
          echo $VITE_FIREBASE_PROJECT_ID
          echo $VITE_FIREBASE_STORAGE_BUCKET
          echo $VITE_FIREBASE_MESSAGING_SENDER_ID
          echo $VITE_FIREBASE_APP_ID
          echo $VITE_FIREBASE_MEASUREMENT_ID
          echo $VITE_EMAIL
          echo $VITE_PASSWORD

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
